[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
sections = ['THIRDPARTY', 'FUTURE', 'STDLIB', 'DJANGO', 'FIRSTPARTY', 'LOCALFOLDER']
known_first_party = ['src']
known_django = ['django']
line_length = 120