# Generated by Django 4.0.2 on 2022-02-22 07:37


from django.db import migrations

from ..models import HealthCheck


def create_counter(*args, **kwargs):
    instance, created = HealthCheck.objects.get_or_create()
    message = "created" if created else "received"
    print(f"Counter {instance} was {message}")


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_healthcheck"),
    ]

    operations = [migrations.RunPython(create_counter)]
